version: '3'
services:
  app:
    build: .
    container_name: furniture-fixed
    environment:
      USER: admin
      PASSWORD: pass
      DATABASE: furniture
      SECRET: _s3cr3t_k3y
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"

  db:
    image: 'mysql/mysql-server:latest'
    container_name: 'furniture-db'
    environment:
      MYSQL_ROOT_PASSWORD: _secret
      MYSQL_DATABASE: furniture
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    

volumes:
  data: